### ISSUE TITLE
Icon aligment in UIBarButtonItem

### ISSUE THREAD

**Issue by ijaureguialzo** [marekmatula/FontIcons.Swift#13]
Hello, I'm unable to vertical align an icon in a UIBarButtonItem. ¿Is there any way to get it right?

This is what I get:

![simulator screen shot 1 mar 2017 9 15 22](https://cloud.githubusercontent.com/assets/6746736/23451379/f7d2dc1c-fe5f-11e6-8959-fe51b915e8ee.png)

I've tried modifying the fonts following [those instructions](http://www.andyyardley.com/2012/04/24/custom-ios-fonts-and-how-to-fix-the-vertical-position-problem/) with no luck.

Any idea?

Thanks in advance.

**Comment by marekmatula** [comment]
I'm not sure.

You should try add a Button to UIBarButtonItem  as mentioned here: http://stackoverflow.com/questions/29060482/changing-vertical-position-of-uibarbuttonitem-on-ios-8-2

**Comment by ijaureguialzo** [comment]
Thank you for pointing in the right direction, I ended doing this:

```
        let button = UIButton(type: .system)
        button.setFontIcon(IonIcon.iosGearOutline, size: 30, forState: .normal)
        let labelSize = button.titleLabel?.intrinsicContentSize
        button.frame = CGRect(origin: CGPoint(x:0,y:0), size: labelSize!)
        button.addTarget(self, action: #selector(YourClass.yourAction), for: .touchUpInside)

        let barBtnItem = UIBarButtonItem(customView: button)
        
        self.toolbarItems?.append(barBtnItem)
```

And now, I get this:

![simulator screen shot 1 mar 2017 13 11 58](https://cloud.githubusercontent.com/assets/6746736/23459565/32ff25f4-fe81-11e6-9667-cc9db7f31bc5.png)
